[View in Colaboratory](https://colab.research.google.com/github/schwaaweb/aimlds1_07-TheMachineLearningFramework/blob/master/M07_CC--DJ--Model_Tuning_CC1.ipynb)

# Splitting data into Test/Train datasets


In this code challenge we're going to use the Pima Indians Diabetes dataset to split our data into test/train datasets both manually and using a library.

In [1]:
# LAMBDA SCHOOL
# 
# MACHINE LEARNING
#
# MIT LICENSE

# Import Data and Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
df = pd.read_csv(url, names=names)
print(df.shape)
df.head()

(768, 9)


preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [3]:
#!wget -c https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv


## 1) Randomly a select 20% of your data to be in your "test" dataset and the other 80% to be in your "train" dataset. Do this without setting a random seed.


In [8]:
df_train, df_test = train_test_split(df, test_size=0.2)

## 2) After you have randomly divided the dataset, print the shape of both of your new test and train datasets and print the first five rows of each.

In [12]:
##### Print train dataset shape and first 5 rows. #####
print(df_train.shape)
print(df_test.head())

(614, 9)
     preg  plas  pres  skin  test  mass   pedi  age  class
126     3   120    70    30   135  42.9  0.452   30      0
639     1   100    74    12    46  19.5  0.149   28      0
456     1   135    54     0     0  26.7  0.687   62      0
31      3   158    76    36   245  31.6  0.851   28      1
234     3    74    68    28    45  29.7  0.293   23      0


In [13]:
##### Print test dataset shape and first 5 rows. #####
print(df_test.shape)
print(df_test.head())

(154, 9)
     preg  plas  pres  skin  test  mass   pedi  age  class
126     3   120    70    30   135  42.9  0.452   30      0
639     1   100    74    12    46  19.5  0.149   28      0
456     1   135    54     0     0  26.7  0.687   62      0
31      3   158    76    36   245  31.6  0.851   28      1
234     3    74    68    28    45  29.7  0.293   23      0


## 3) Use sklearn's train_test_split function to split the data into test and training datasets. Set the random_state to 42

In [14]:
df_trainr42, df_testr42 = train_test_split(df, test_size=0.2, random_state=42)

## 4) Print the shape and first 5 rows of the new dataframes.

In [19]:
##### Print train dataset shape and first 5 rows. #####
print(df_trainr42.shape)
print(df_trainr42.head())

(614, 9)
     preg  plas  pres  skin  test  mass   pedi  age  class
60      2    84     0     0     0   0.0  0.304   21      0
618     9   112    82    24     0  28.2  1.282   50      1
346     1   139    46    19    83  28.7  0.654   22      0
294     0   161    50     0     0  21.9  0.254   65      0
231     6   134    80    37   370  46.2  0.238   46      1


In [20]:
##### Print test dataset shape and first 5 rows. #####
print(df_testr42.shape)
print(df_testr42.head())

(154, 9)
     preg  plas  pres  skin  test  mass   pedi  age  class
668     6    98    58    33   190  34.0  0.430   43      0
324     2   112    75    32     0  35.7  0.148   21      0
624     2   108    64     0     0  30.8  0.158   21      0
690     8   107    80     0     0  24.6  0.856   34      0
473     7   136    90     0     0  29.9  0.210   50      0


### Change the random state on your test_train_split to a different integer and run the code again. What happens to the shape of the dataset? What happens to the first five rows?


---



The shape of the dataset remains the same, but the order of the rows changes.

In [21]:
df_trainr13, df_testr13 = train_test_split(df, test_size=0.2, random_state=13)
print(df_trainr13.shape)
print(df_trainr13.head())
print(df_testr13.shape)
print(df_testr13.head())

(614, 9)
     preg  plas  pres  skin  test  mass   pedi  age  class
192     7   159    66     0     0  30.4  0.383   36      1
445     0   180    78    63    14  59.4  2.420   25      1
573     2    98    60    17   120  34.7  0.198   22      0
233     4   122    68     0     0  35.0  0.394   29      0
133     8    84    74    31     0  38.3  0.457   39      0
(154, 9)
     preg  plas  pres  skin  test  mass   pedi  age  class
524     3   125    58     0     0  31.6  0.151   24      0
275     2   100    70    52    57  40.5  0.677   25      0
587     6   103    66     0     0  24.3  0.249   29      0
356     1   125    50    40   167  33.3  0.962   28      1
710     3   158    64    13   387  31.2  0.295   24      0


## 5) Using the original dataframe, create two new dataframes titled "X" and "Y". 

The Y dataframe should be composed of only the "class" column (our dependent variable - or what we want to predict) and the X dataframe should be composed of all other columns. (Our independent variables, sometimes called features or predictors)

Print their shape as well as the first 5 rows of these two dataframes.


In [29]:
##### YOUR CODE HERE #####
Y = df[['class']] # double square brackets
print(Y.shape)
Y.head()

(768, 1)


class
0      1
1      0
2      1
3      0
4      1

In [31]:
X = df.drop(['class'], axis=1)
print(X.shape)
X.head()

(768, 8)


preg  plas  pres  skin  test  mass   pedi  age
0     6   148    72    35     0  33.6  0.627   50
1     1    85    66    29     0  26.6  0.351   31
2     8   183    64     0     0  23.3  0.672   32
3     1    89    66    23    94  28.1  0.167   21
4     0   137    40    35   168  43.1  2.288   33

In [32]:
print(df.shape)
df.head()

(768, 9)


preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

## 6) Now use the test_train_split function to not only split your dataset into test and train datasets, but also by independent and dependent variables. Pick any integer value to use use as the random seed.

You should end up with 4 datasets: X_train, Y_train, X_test, and Y_test

Print the sizes and first 5 rows of each of these four datasets.

In [ ]:
##### YOUR CODE HERE #####

In [33]:
X_train, X_test = train_test_split(X, test_size=0.2, random_state=17)
print(X_train.shape)
print(X_train.head())
print(X_test.shape)
print(X_test.head())

(614, 8)
     preg  plas  pres  skin  test  mass   pedi  age
679     2   101    58    17   265  24.2  0.614   23
134     2    96    68    13    49  21.1  0.647   26
250     9   106    52     0     0  31.2  0.380   42
470     1   144    82    40     0  41.3  0.607   28
668     6    98    58    33   190  34.0  0.430   43
(154, 8)
     preg  plas  pres  skin  test  mass   pedi  age
649     0   107    60    25     0  26.4  0.133   23
516     9   145    88    34   165  30.3  0.771   53
151     4   114    65     0     0  21.9  0.432   37
381     0   105    68    22     0  20.0  0.236   22
325     1   157    72    21   168  25.6  0.123   24


In [34]:
Y_train, Y_test = train_test_split(Y, test_size=0.2, random_state=17)
print(Y_train.shape)
print(Y_train.head())
print(Y_test.shape)
print(Y_test.head())

(614, 1)
     class
679      0
134      0
250      0
470      0
668      0
(154, 1)
     class
649      0
516      1
151      0
381      0
325      0


## The following code will split our data and then train a logistic regression classifier.

## Run the code muliple times using different random_seed. What happens to the model's accuracy? Why do you think  this might be happening? 

## Research what the "Random Seed" is for and how it can help us ensure that our machine learning results are reproducible.

In [43]:
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression

feature_cols = [col for col in df.columns if 'class' not in col]
Y = df['class']
X = df[feature_cols]

random_seed = 42

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.2, random_state=random_seed)
model = LogisticRegression()
model.fit(X_train, Y_train)
result = model.score(X_test, Y_test)
print("Accuracy: %.3f%%\n" % (result*100.0))
print('\nX_train')
print(X_train.shape)
print(X_train.head())
print('\nX_test')
print(X_test.shape)
print(X_test.head())
print('\nY_train')
print(Y_train.shape)
print(Y_train.head())
print('\nY_test')
print(Y_test.shape)
print(Y_test.head())

Accuracy: 75.974%


X_train
(614, 8)
     preg  plas  pres  skin  test  mass   pedi  age
60      2    84     0     0     0   0.0  0.304   21
618     9   112    82    24     0  28.2  1.282   50
346     1   139    46    19    83  28.7  0.654   22
294     0   161    50     0     0  21.9  0.254   65
231     6   134    80    37   370  46.2  0.238   46

X_test
(154, 8)
     preg  plas  pres  skin  test  mass   pedi  age
668     6    98    58    33   190  34.0  0.430   43
324     2   112    75    32     0  35.7  0.148   21
624     2   108    64     0     0  30.8  0.158   21
690     8   107    80     0     0  24.6  0.856   34
473     7   136    90     0     0  29.9  0.210   50

Y_train
(614,)
60     0
618    1
346    0
294    0
231    1
Name: class, dtype: int64

Y_test
(154,)
668    0
324    0
624    0
690    0
473    0
Name: class, dtype: int64


In [44]:
np.random.seed(42)
np.random.random(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [45]:
np.random.random(5)

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [48]:
np.random.seed(42) # the seed makes the 'random' number that follow repeatable
np.random.random(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [47]:
np.random.random(5)

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])