[View in Colaboratory](https://colab.research.google.com/github/schwaaweb/aimlds1_07-TheMachineLearningFramework/blob/master/M07_CCS--TC--Solution_of_Model_Tuning_CC1.ipynb)

# Splitting data into Test/Train datasets


In this code challenge we're going to use the Pima Indians Diabetes dataset to split our data into test/train datasets both manually and using a library.

In [3]:
# LAMBDA SCHOOL
# 
# MACHINE LEARNING
#
# MIT LICENSE

# Import Data and Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
df = pd.read_csv(url, names=names)
print(df.shape)
df.head()

(768, 9)


preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1


## 1) Randomly a select 20% of your data to be in your "test" dataset and the other 80% to be in your "train" dataset. Do this without setting a random seed.


In [45]:
train_set_size = int(0.8 * len(df))
test_set_size = len(df) - train_set_size
print(train_set_size)
print(test_set_size)

# Reorder df so that our train and test sets are randomized
df_reordered = np.random.permutation(len(df))
#train_set = df[df_reordered[0:train_set_size]]
# test_set = df[df_reordered[train_set_size+1:]]

np.random.seed(42)
train_set_manual = df.sample(frac=0.8)
test_set_manual = df.drop(train_set_manual.index)


614
154


## 2) After you have randomly divided the dataset, print the shape of both of your new test and train datasets and print the first five rows of each.

In [46]:
##### Print train dataset shape and first 5 rows. #####
print(train_set_manual.shape)
print(train_set_manual.head())

(614, 9)
     preg  plas  pres  skin  test  mass   pedi  age  class
224     1   100    66    15    56  23.6  0.666   26      0
688     1   140    74    26   180  24.1  0.828   23      0
475     0   137    84    27     0  27.3  0.231   59      0
152     9   156    86    28   155  34.3  1.189   42      1
474     4   114    64     0     0  28.9  0.126   24      0


In [25]:
##### Print test dataset shape and first 5 rows. #####
print(test_set_manual.shape)
print(test_set_manual.head())

(154, 9)
    preg  plas  pres  skin  test  mass   pedi  age  class
2      8   183    64     0     0  23.3  0.672   32      1
9      8   125    96     0     0   0.0  0.232   54      1
16     0   118    84    47   230  45.8  0.551   31      1
18     1   103    30    38    83  43.3  0.183   33      0
24    11   143    94    33   146  36.6  0.254   51      1


## 3) Use sklearn's train_test_split function to split the data into test and training datasets. Set the random_state to 42

In [0]:
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

## 4) Print the shape and first 5 rows of the new dataframes.

In [48]:
print(train_df.shape)
print(train_df.head())

(614, 9)
     preg  plas  pres  skin  test  mass   pedi  age  class
514     3    99    54    19    86  25.6  0.154   24      0
145     0   102    75    23     0   0.0  0.572   21      0
701     6   125    78    31     0  27.6  0.565   49      1
314     7   109    80    31     0  35.9  1.127   43      1
694     2    90    60     0     0  23.5  0.191   25      0


In [32]:
print(test_df.shape)
print(test_df.head())

(154, 9)
     preg  plas  pres  skin  test  mass   pedi  age  class
668     6    98    58    33   190  34.0  0.430   43      0
324     2   112    75    32     0  35.7  0.148   21      0
624     2   108    64     0     0  30.8  0.158   21      0
690     8   107    80     0     0  24.6  0.856   34      0
473     7   136    90     0     0  29.9  0.210   50      0


### Change the random state on your test_train_split to a different integer and run the code again. What happens to the shape of the dataset? What happens to the first five rows?


---



## 5) Using the original dataframe, create two new dataframes titled "X" and "Y". 

The Y dataframe should be composed of only the "class" column (our dependent variable - or what we want to predict) and the X dataframe should be composed of all other columns. (Our independent variables, sometimes called features or predictors)

Print their shape as well as the first 5 rows of these two dataframes.


In [0]:
Y = df['class']
X = df.drop(['class'],axis=1)

In [52]:
print(X.shape)
print(X.head())

(768, 8)
   preg  plas  pres  skin  test  mass   pedi  age
0     6   148    72    35     0  33.6  0.627   50
1     1    85    66    29     0  26.6  0.351   31
2     8   183    64     0     0  23.3  0.672   32
3     1    89    66    23    94  28.1  0.167   21
4     0   137    40    35   168  43.1  2.288   33


In [53]:

print(Y.shape)
print(Y.head())

(768,)
0    1
1    0
2    1
3    0
4    1
Name: class, dtype: int64


## 6) Now use the test_train_split function to not only split your dataset into test and train datasets, but also by independent and dependent variables. Pick any integer value to use use as the random seed.

You should end up with 4 datasets: X_train, Y_train, X_test, and Y_test

Print the sizes and first 5 rows of each of these four datasets.

In [0]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [61]:
print(X_train.shape)
print(X_train.head())

(614, 8)
     preg  plas  pres  skin  test  mass   pedi  age
60      2    84     0     0     0   0.0  0.304   21
618     9   112    82    24     0  28.2  1.282   50
346     1   139    46    19    83  28.7  0.654   22
294     0   161    50     0     0  21.9  0.254   65
231     6   134    80    37   370  46.2  0.238   46


In [62]:
print(Y_train.shape)
print(Y_train.head())

(614,)
60     0
618    1
346    0
294    0
231    1
Name: class, dtype: int64


In [64]:

print(X_test.shape)
print(X_test.head())

(154, 8)
     preg  plas  pres  skin  test  mass   pedi  age
668     6    98    58    33   190  34.0  0.430   43
324     2   112    75    32     0  35.7  0.148   21
624     2   108    64     0     0  30.8  0.158   21
690     8   107    80     0     0  24.6  0.856   34
473     7   136    90     0     0  29.9  0.210   50


In [65]:
print(Y_test.shape)
print(Y_test.head())

(154,)
668    0
324    0
624    0
690    0
473    0
Name: class, dtype: int64


## The following code will split our data and then train a logistic regression classifier.

## Run the code muliple times using different random_seed. What happens to the model's accuracy? Why do you think  this might be happening? 

## Research what the "Random Seed" is for and how it can help us ensure that our machine learning results are reproducible.

In [69]:
from sklearn.linear_model import LogisticRegression

feature_cols = [col for col in df.columns if 'class' not in col]
Y = df['class']
X = df[feature_cols]

random_seed = 42

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=random_seed)
model = LogisticRegression()
model.fit(X_train, Y_train)
result = model.score(X_test, Y_test)
print("Accuracy: %.3f%%" % (result*100.0))

Accuracy: 75.974%


In [72]:
# Computers are _deterministic_

np.random.seed(42)
print(np.random.random(5))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [73]:
print(np.random.random(5))

[0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]


In [76]:
np.random.seed(42)
print(np.random.random(5))
print(np.random.random(5))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]


In [77]:
np.random.seed(43)
print(np.random.random(5))
print(np.random.random(5))

[0.11505457 0.60906654 0.13339096 0.24058962 0.32713906]
[0.85913749 0.66609021 0.54116221 0.02901382 0.7337483 ]


In [83]:
# 101010

r = 42.0 / 123123123123123
r = r / 123123123123123
r = r / 123123123123123
r = r / 123123123123123
r = r / 123123123123123

print(r)

1.48440078153e-69


In [80]:
"{0:b}".format(r)

ValueError: ignored